#!/bin/bash

pluginloader="internal/process/pluginloader.go"

echo "// This file is autogenerated. Do not edit.

package process

import (" >"$pluginloader"
grep -v '^#\|^\s*$' plugin.cfg | while read -r line; do
  plugin_name=$(echo "$line" | cut -d ":" -f 1)
  plugin_path=$(echo "$line" | cut -d ":" -f 2)
  echo "  _ \"$plugin_path\"" >>"$pluginloader"
done
echo ")" >>"$pluginloader"
