#!/bin/bash

echo -n "Generating plugins: "

pluginloader="internal/process/pluginloader.go"

echo "// This file is autogenerated. Do not edit.

package process

import (" >"$pluginloader"

while read -r line; do
  if [[ "$line" == \#* || -z "$line" ]]; then continue; fi # Skip blank and comment lines
  pluginname=$(echo "$line" | cut -d ":" -f 1)
  pluginpath=$(echo "$line" | cut -d ":" -f 2)
  echo "	_ \"$pluginpath\"" >>"$pluginloader"
  echo -n $pluginname
done <"plugin.cfg"
echo ")" >>"$pluginloader"

echo "...done" # newline to end plugin console line
