#!/bin/bash

pluginloader="internal/process/pluginloader.go"

prefix="// This file is autogenerated. Do not edit.

package process"

echo "$prefix
import (" >"$pluginloader"

plugins=false
grep -v '^#\|^\s*$' plugin.cfg | while read -r line; do
  plugins=true
  plugin_name=$(echo "$line" | cut -d ":" -f 1)
  plugin_path=$(echo "$line" | cut -d ":" -f 2)
  echo "	_ \"$plugin_path\"" >>"$pluginloader"
done
echo ")" >>"$pluginloader"

if ! $plugins; then
  echo "$prefix" > "$pluginloader"
fi
