name: Deploy pathvector.io

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "generate.sh"
      - ".github/workflows/docs.yml"
      - "*.go"

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Generate docs
        run: go generate

      - name: Build docs
        run: cd docs && npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/build/
          fqdn: pathvector.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
